// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQL_API.Data;

#nullable disable

namespace SQL_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251028113722_ionity")]
    partial class ionity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SQL_API.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DriverId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            DriverId = 101,
                            DriverName = "Rajesh Patil"
                        },
                        new
                        {
                            DriverId = 102,
                            DriverName = "Sneha Kulkarni"
                        },
                        new
                        {
                            DriverId = 103,
                            DriverName = "Kiran Deshmukh"
                        },
                        new
                        {
                            DriverId = 104,
                            DriverName = "Anjali Sharma"
                        });
                });

            modelBuilder.Entity("SQL_API.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("TripId");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            TripId = 1,
                            Destination = "Mumbai",
                            DriverId = 101,
                            Source = "Pune",
                            Status = "Completed",
                            VehicleId = 1
                        },
                        new
                        {
                            TripId = 2,
                            Destination = "Aurangabad",
                            DriverId = 102,
                            Source = "Nashik",
                            Status = "Ongoing",
                            VehicleId = 2
                        },
                        new
                        {
                            TripId = 3,
                            Destination = "Amravati",
                            DriverId = 103,
                            Source = "Nagpur",
                            Status = "Scheduled",
                            VehicleId = 3
                        },
                        new
                        {
                            TripId = 4,
                            Destination = "Nashik",
                            DriverId = 104,
                            Source = "Pune",
                            Status = "Scheduled",
                            VehicleId = 4
                        },
                        new
                        {
                            TripId = 5,
                            Destination = "Pune",
                            DriverId = 101,
                            Source = "Mumbai",
                            Status = "Scheduled",
                            VehicleId = 5
                        },
                        new
                        {
                            TripId = 6,
                            Destination = "Nashik",
                            DriverId = 102,
                            Source = "Aurangabad",
                            Status = "Scheduled",
                            VehicleId = 1
                        },
                        new
                        {
                            TripId = 7,
                            Destination = "Nagpur",
                            DriverId = 103,
                            Source = "Amravati",
                            Status = "Scheduled",
                            VehicleId = 2
                        },
                        new
                        {
                            TripId = 8,
                            Destination = "Aurangabad",
                            DriverId = 104,
                            Source = "Pune",
                            Status = "Scheduled",
                            VehicleId = 3
                        },
                        new
                        {
                            TripId = 9,
                            Destination = "Nagpur",
                            DriverId = 101,
                            Source = "Mumbai",
                            Status = "Scheduled",
                            VehicleId = 4
                        },
                        new
                        {
                            TripId = 10,
                            Destination = "Pune",
                            DriverId = 102,
                            Source = "Nashik",
                            Status = "Scheduled",
                            VehicleId = 5
                        });
                });

            modelBuilder.Entity("SQL_API.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            Type = "Van",
                            VehicleModel = "Tata Ace",
                            VehicleNumber = "MH12AB1234"
                        },
                        new
                        {
                            VehicleId = 2,
                            Type = "Truck",
                            VehicleModel = "Eicher Pro",
                            VehicleNumber = "MH14CD5678"
                        },
                        new
                        {
                            VehicleId = 3,
                            Type = "Mini Van",
                            VehicleModel = "Maruti Omni",
                            VehicleNumber = "MH31EF7890"
                        },
                        new
                        {
                            VehicleId = 4,
                            Type = "Bus",
                            VehicleModel = "Volvo 9400",
                            VehicleNumber = "MH22GH1234"
                        },
                        new
                        {
                            VehicleId = 5,
                            Type = "Van",
                            VehicleModel = "Mahindra Supro",
                            VehicleNumber = "MH33JK5678"
                        });
                });

            modelBuilder.Entity("SQL_API.Models.Trip", b =>
                {
                    b.HasOne("SQL_API.Models.Driver", "Driver")
                        .WithMany("Trips")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SQL_API.Models.Vehicle", "Vehicle")
                        .WithMany("Trips")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SQL_API.Models.Driver", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("SQL_API.Models.Vehicle", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
